version: "3.8"

services:
  web:
    image: php:8.1.18-fpm-alpine
    command: sh -c "php-fpm"
    restart: always
    working_dir: /var/www/
    volumes:
      - .:/var/www

  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - .:/etc/nginx/conf.d